export const INIT =  'init'
export const ROUTE =  'route'
export const REDIRECT =  'redirect'
export const VERIFY_TOKEN_SUCCEEDED = 'VERIFY_TOKEN_SUCCEEDED'
export const VERIFY_TOKEN_STARTED = 'VERIFY_TOKEN_STARTED'
export const VERIFY_TOKEN_FAILED = 'VERIFY_TOKEN_FAILED'
