export const GET_ACCOUNTS_SUCCESS = 'GET_ACCOUNTS_SUCCESS'
export const GET_ACCOUNTS_STARTED = 'GET_ACCOUNTS_STARTED'
export const GET_ACCOUNTS_FAILURE = 'GET_ACCOUNTS_FAILURE'
export const CHANGE_PAGE = 'CHANGE_PAGE'